version: '2.1'

services:

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: "mqtt"
    restart: always
    network_mode: host
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /volume1/docker/home-assistant/mqtt/data:/mosquitto/data
      - /volume1/docker/home-assistant/mqtt/config:/mosquitto/config
      - /volume1/docker/home-assistant/mqtt/log:/mosquitto/log
    environment: 
      - TZ=America/Toronto

  grafana:
    image: grafana/grafana:latest
    container_name: "grafana"
    depends_on: 
      influxdb:
        condition: service_healthy
    environment: 
      GF_RENDERING_SERVER_URL: http://192.168.1.100:8081/render
      GF_RENDERING_CALLBACK_URL: http://192.168.1.100:3000/
      GF_LOG_FILTERS: rendering:debug
    network_mode: host
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - /volume1/docker/home-assistant/grafana:/var/lib/grafana

  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: "grafana-renderer"
    depends_on: 
      grafana:
        condition: service_started
    ports:
      - 8081:8081

  influxdb:
    image: influxdb:latest
    container_name: "influxdb"
    healthcheck:
      test: ["CMD", "curl", "-sI", "http://127.0.0.1:8086/ping"]
      interval: 30s
      timeout: 1s
      retries: 24
    environment:
      - TZ=America/New_York
    network_mode: host
    ports:
      - 8083:8083
      - 8086:8086
    restart: on-failure
    volumes:
      - /volume1/docker/home-assistant/influxdb:/var/lib/influxdb

  home-assistant:
    image: homeassistant/home-assistant:latest
    container_name: "hass"
    restart: always
    depends_on:
      influxdb:
        condition: service_healthy
      mqtt:
        condition: service_started
    network_mode: host
    ports:
      - 443:443
    volumes:
      - /volume1/docker/home-assistant/homeassistant/config:/config
    environment:
      - TZ=America/New_York