version: '3.8'

networks:
  newasgard:
    external: true

services:

  # ---------------------------------------------------------------

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: "mqtt"
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /home/$USER/ha-docker-support/mqtt/data:/mosquitto/data
      - /home/$USER/ha-docker-support/mqtt/config:/mosquitto/config
      - /home/$USER/ha-docker-support/mqtt/log:/mosquitto/log
    environment:
      - TZ=America/New_York
    networks:
      newasgard:
        ipv4_address: 10.107.1.108

  # ---------------------------------------------------------------

  esphome:
    container_name: esphome
    image: esphome/esphome
    volumes:
      - /home/$USER/ha-docker-support/homeassistant/config/esphome:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host
    depends_on:
      - homeassistant

  homeassistant:
    image: homeassistant/home-assistant:latest     #Latest Production
    container_name: "homeassistant"
    restart: always
    depends_on:
      - mqtt
    ports:
      - 443:443
      - 8123:8123
    volumes:
      - /home/$USER/ha-docker-support/homeassistant/config:/config
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - TZ=America/New_York
    networks:
      newasgard:
        ipv4_address: 10.107.1.107


  # ---------------------------------------------------------------

  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /home/$USER/ha-docker-support/code_server:/config
      - /home/$USER/ha-docker-support/homeassistant/config:/config/workspace
    ports:
      - 8443:8443
    restart: unless-stopped

  # ---------------------------------------------------------------

  influxdb:
    image: influxdb:2.1.1
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./influx_entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086
    networks:
      newasgard:
        ipv4_address: 10.107.1.109
    
  # ---------------------------------------------------------------

  grafana:
    image: grafana/grafana-oss:8.4.3
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000
    networks:
      newasgard:
        ipv4_address: 10.107.1.110

volumes:
  grafana-storage:
  influxdb-storage: