version: '3.8'

services:

  # ---------------------------------------------------------------

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: "mqtt"
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /home/$USER/ha-docker-support/mqtt/data:/mosquitto/data
      - /home/$USER/ha-docker-support/mqtt/config:/mosquitto/config
      - /home/$USER/ha-docker-support/mqtt/log:/mosquitto/log
    environment:
      - TZ=America/New_York

  # ---------------------------------------------------------------

  homeassistant:
    image: homeassistant/home-assistant:latest     #Latest Production
    container_name: "homeassistant"
    restart: always
    depends_on:
      - mqtt
    ports:
      - 443:443
      - 8123:8123
    volumes:
      - /home/$USER/ha-docker-support/homeassistant/config:/config
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - TZ=America/New_York

  # ---------------------------------------------------------------

  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /home/$USER/ha-docker-support/code_server:/config
      - /home/$USER/ha-docker-support/homeassistant/config:/config/workspace
    ports:
      - 8443:8443
    restart: unless-stopped
